# -*- coding: utf-8 -*-
"""Week9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1de35eTkvAB-mkRS07uLBCZccvNf7qMrn
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread("corn.jpg")

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

blur = cv2.GaussianBlur(gray, (5, 5), 0)

ret, thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

white_ratio = np.sum(thresh == 255) / thresh.size
if white_ratio < 0.2:
    thresh = cv2.bitwise_not(thresh)

kernel = np.ones((3, 3), np.uint8)
opening = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel, iterations=2)

sure_bg = cv2.dilate(opening, kernel, iterations=3)

dist_transform = cv2.distanceTransform(opening, cv2.DIST_L2, 5)
ret, sure_fg = cv2.threshold(dist_transform, 0.3 * dist_transform.max(), 255, 0)

sure_fg = np.uint8(sure_fg)

unknown = cv2.subtract(sure_bg, sure_fg)

ret, markers = cv2.connectedComponents(sure_fg)

markers = markers + 1

markers[unknown == 255] = 0

markers = cv2.watershed(image, markers)

output = np.zeros((image.shape[0], image.shape[1], 3), dtype=np.uint8)

labels = np.unique(markers)

count = 0

for label in labels:
    if label > 1:
        count += 1
        color = np.random.randint(0, 255, size=3)
        output[markers == label] = color

print("Number of corns:", count)

cv2.imwrite("output.png", output)

plt.imshow(cv2.cvtColor(output, cv2.COLOR_BGR2RGB))

plt.title("Watershed Regions")
plt.axis("off")

plt.show()