# -*- coding: utf-8 -*-
"""week8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4JgtJJWOPVs7bnfJUxIFgllTtnq1Nuf
"""

import numpy as np
from PIL import Image
import os

def load(path):
    img = Image.open(path).convert("RGB")
    return np.array(img)

# grayscale
def gray(img):
    return (0.299*img[:,:,0] + 0.587*img[:,:,1] + 0.114*img[:,:,2]).astype(np.uint8)

# remove noise
def blur(img):
    k = 3
    pad = 1
    padded = np.pad(img, pad, mode="edge")
    out = np.zeros_like(img)

    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            out[i,j] = np.median(padded[i:i+k, j:j+k])

    return out

# improve contrast
def contrast(img):
    hist = np.zeros(256)

    for p in img.flatten():
        hist[p] += 1

    cdf = np.cumsum(hist)
    cdf = (cdf - cdf.min()) * 255 / (cdf.max() - cdf.min())
    cdf = cdf.astype(np.uint8)

    return cdf[img]

# auto threshold
def get_thresh(img):
    hist = np.bincount(img.flatten(), minlength=256)
    total = img.size
    sum_all = np.dot(np.arange(256), hist)

    sum_bg = 0
    w_bg = 0
    best = 0
    max_var = 0

    for t in range(256):
        w_bg += hist[t]
        if w_bg == 0:
            continue

        w_fg = total - w_bg
        if w_fg == 0:
            break

        sum_bg += t * hist[t]

        m_bg = sum_bg / w_bg
        m_fg = (sum_all - sum_bg) / w_fg

        var = w_bg * w_fg * (m_bg - m_fg) ** 2

        if var > max_var:
            max_var = var
            best = t

    return best

# make it black & white
def binary(img, t):
    return (img > t).astype(np.uint8) * 255

def erode(img):
    padded = np.pad(img, 1, mode="constant", constant_values=255)
    out = np.zeros_like(img)

    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            out[i,j] = np.min(padded[i:i+3, j:j+3])

    return out

def dilate(img):
    padded = np.pad(img, 1, mode="constant", constant_values=0)
    out = np.zeros_like(img)

    for i in range(img.shape[0]):
        for j in range(img.shape[1]):
            out[i,j] = np.max(padded[i:i+3, j:j+3])

    return out

def clean(img):
    return erode(dilate(erode(img)))

def remove_small(img, min_size=80):
    h, w = img.shape
    seen = np.zeros((h,w))
    out = np.zeros((h,w))

    def neigh(x,y):
        for dx in [-1,0,1]:
            for dy in [-1,0,1]:
                nx, ny = x+dx, y+dy
                if 0 <= nx < h and 0 <= ny < w:
                    yield nx, ny

    for i in range(h):
        for j in range(w):
            if img[i,j] == 255 and seen[i,j] == 0:
                stack = [(i,j)]
                comp = []

                while stack:
                    x,y = stack.pop()
                    if seen[x,y]:
                        continue

                    seen[x,y] = 1
                    comp.append((x,y))

                    for nx,ny in neigh(x,y):
                        if img[nx,ny] == 255 and seen[nx,ny] == 0:
                            stack.append((nx,ny))

                if len(comp) >= min_size:
                    for x,y in comp:
                        out[x,y] = 255

    return out.astype(np.uint8)

def edges(img):
    h,w = img.shape
    out = np.zeros((h,w))

    for i in range(h):
        for j in range(w):
            if img[i,j] == 255:
                for dx in [-1,0,1]:
                    for dy in [-1,0,1]:
                        ni = i+dx
                        nj = j+dy

                        if 0 <= ni < h and 0 <= nj < w:
                            if img[ni,nj] == 0:
                                out[i,j] = 255
                        else:
                            out[i,j] = 255

    return out.astype(np.uint8)

def draw(binary, contour):
    h,w = binary.shape
    rgb = np.zeros((h,w,3), dtype=np.uint8)

    for i in range(h):
        for j in range(w):
            if binary[i,j] == 255:
                rgb[i,j] = [255,255,255]
            else:
                rgb[i,j] = [0,0,0]

            if contour[i,j] == 255:
                rgb[i,j] = [0,255,0]

    return rgb

def run(path):
    os.makedirs("output", exist_ok=True)

    img = load(path)
    g = gray(img)
    b = blur(g)
    c = contrast(b)

    t = get_thresh(c)
    bw = binary(c, t)

    clean_img = clean(bw)
    clean_img = remove_small(clean_img)

    e = edges(clean_img)
    final = draw(clean_img, e)

    Image.fromarray(final).save("output.png")

run("donuts.jpg")